### PR TITLE
Front end testing

### PR DESCRIPTION
**Pull request by claire-melbourne**
Screen Shot 2020-10-01 at 12 06 50 PM
passing api tests and react test

### CODE REVIEW

**Review by owenwexler — APPROVED** [review]
Looks good.... not looking forward to trying to implement this in my front end but glad you got it working.

**Comment by claire-melbourne** [comment]
Let me know if you have questions on it, happy to share screens and talk through it!

**Comment by claire-melbourne** [comment]
captured
I accidentally made these changes on my front end test! Sorry for disorganization with that, would like to merge this before I delete branch and get master up to date so I don't make any more git messes!

**Comment by owenwexler** [comment]
I don't see any new commits, only the two that were there before?

**Comment by claire-melbourne** [comment]
Oof! Was so excited about my gif that I forgot to actually commit the changes. They are up now.

**Review by owenwexler — APPROVED** [review]
Looks good!  Just make sure you take out the debugger;s when appropriate

**Pull request merged**
